#!/bin/bash -e

## A simple wrapper to allow development to occur in a container.

container="aklite-dev"
DEF_COMPILER_ARGS="-e CC=clang -e CXX=clang++"

here=$(dirname $(readlink -f $0))
cd $here

if ! docker image inspect $container 2>/dev/null 1>/dev/null ; then
	echo "Container not found, doing one time docker build"
	docker build -t $container -f ./docker/Dockerfile .
fi

if [ -n "$CCACHE_DIR" ] ; then
	CCACHE_DIR=$(readlink -f $CCACHE_DIR)
	CCACHE_ARGS="-e CCACHE_DIR=$CCACHE_DIR -v$CCACHE_DIR:$CCACHE_DIR"
else
	CCACHE_ARGS="-e CCACHE_DIR=/tmp/ccache"
fi

set -x
if [ -n "${TEST}" ]; then
	exec docker run --privileged $DEF_COMPILER_ARGS $CCACHE_ARGS --entrypoint="wrapdocker" --rm -it -v $here:$here -w $here $container $*
else
	exec docker run --privileged $DEF_COMPILER_ARGS $CCACHE_ARGS -u $(id -u):$(id -g) --rm -it -v $here:$here -w $here $container $*
fi
