#!/bin/bash -e

here=$(dirname $(readlink -f $0))
cd $here

if [ $# -eq 0 ] ; then
	echo "Launching unit tests in docker"
	exec ./dev-shell ./unit-test indocker
fi

set -x

build=$(mktemp -d -p $here)
cd $build

# do clang-tidy during compilation
../cmake-init.sh -DBUILD_WITH_CLANG_TIDY=ON
ninja aklite-tests

# do additional clang-tidying in the aktualizr way
clang_tests=$(ninja help | grep aktualizr_clang_tidy-src- | cut -d: -f1)
ninja $clang_tests

# do clang-formating in the aktualizr way
clang_tests=$(ninja help | grep aktualizr_ci_clang_format-src- | cut -d: -f1)
ninja $clang_tests

ctest -V -R test_lite-helpers
ctest -V -R test_compose-apps
ctest -V -R test_aktualizr-lite

# test building the sota tools
rm -rf ./*
../cmake-init.sh -DBUILD_DOCKERAPP=OFF -DBUILD_SOTA_TOOLS=ON
ninja all
if [[ ! -f ./aktualizr/src/sota_tools/garage-sign/bin/garage-sign ]]; then
  echo "Failed to build garage-sign!"
  exit 1
fi
if [[ ! -f ./aktualizr/src/sota_tools/garage-push ]]; then
  echo "Failed to build garage-push!"
  exit 1
fi
