#!/bin/bash -e

here=$(dirname $(readlink -f $0))
cd $here

if [ $# -eq 0 ] ; then
	echo "Launching unit tests in docker"
	exec ./dev-shell ./unit-test indocker
fi

set -x

build=$(mktemp -d -p $here)
cd $build

../cmake-init.sh -DCLANG_TIDY=ON
ninja aklite-tests

ctest -V -R test_lite-helpers
ctest -V -R test_aktualizr-lite
