name: Aklite CI Tests
on:
  push:
  pull_request_target:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: read

jobs:
  clang:
    name: Clang Format And Tidy
    runs-on: ubuntu-latest
    container:
      image: foundries/aklite-dev
      env:
        CXX: clang++
        CC: clang
        CCACHE_DIR: /tmp/ccache

    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory /__w/aktualizr-lite/aktualizr-lite
      - run: git submodule update --init --recursive
      - name: config
        run: make -f dev-flow.mk config
      - name: format
        run: make -f dev-flow.mk format
      - name: tidy
        run: make -f dev-flow.mk tidy

  garage-tools:
    name: Build Garage Tools
    runs-on: ubuntu-latest
    container:
      image: foundries/aklite-dev
      env:
        CXX: clang++
        CC: clang
        CCACHE_DIR: /tmp/ccache

    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory /__w/aktualizr-lite/aktualizr-lite
      - run: git submodule update --init --recursive
      - name: build garage tools
        run: make -f dev-flow.mk garage-tools
      - name: check garage tools
        run: |
          if [[ ! -f build-garage/aktualizr/src/sota_tools/garage-sign/bin/garage-sign ]]; then
            echo "Failed to build garage-sign!"
            exit 1
          fi
          if [[ ! -f build-garage/aktualizr/src/sota_tools/garage-push ]]; then
            echo "Failed to build garage-push!"
            exit 1
          fi

  test:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: foundries/aklite-dev
      env:
        CXX: clang++
        CC: clang
        CCACHE_DIR: /tmp/ccache
    steps:
      - uses: actions/checkout@v3
      - run: git config --global --add safe.directory /__w/aktualizr-lite/aktualizr-lite
      - run: git submodule update --init --recursive
      - name: test
        run: make -f dev-flow.mk config build test
